// src/UI/Vue/src/views/auth/forgot-password.vue
<template>
    <div
        class="flex justify-center items-center min-h-screen bg-[url('/assets/images/map.svg')] dark:bg-[url('/assets/images/map-dark.svg')] bg-cover bg-center"
    >
        <div class="panel sm:w-[480px] m-6 max-w-lg w-full">
            <h2 class="font-bold text-2xl mb-3">Forgot Password</h2>
            <p class="mb-7">Enter your email to recover your ID</p>
            <form class="space-y-5" @submit.prevent="router.push('/')">
                <div>
                    <label for="email">Email</label>
                    <input id="email" type="email" class="form-input" placeholder="Enter Email" />
                </div>
                <button type="submit" class="btn btn-primary w-full">RECOVER</button>
            </form>
        </div>
    </div>
</template>
<script lang="ts" setup>
    import { useRouter } from 'vue-router';
    import { useMeta } from '@/composables/use-meta';
    useMeta({ title: 'Forgot Password' });
    const router = useRouter();
</script>

// src/UI/Angular/src/app/module/auth/pages/forgot-password/forgot-password.component.ts
import { Component, inject } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-forgot-password',
  standalone: true,
  imports: [],
  templateUrl: './forgot-password.component.html',
  styleUrl: './forgot-password.component.css',
})
export class ForgotPasswordComponent {
  router = inject(Router);
}

<div class="flex min-h-screen items-center justify-center bg-[url('/assets/images/map.svg')] bg-cover bg-center dark:bg-[url('/assets/images/map-dark.svg')]">
    <div class="panel m-6 w-full max-w-lg sm:w-[480px]">
        <h2 class="mb-3 text-2xl font-bold">Password Reset</h2>
        <p class="mb-7">Enter your email to recover your ID</p>
        <form class="space-y-5">
            <div>
                <label for="email">Email</label>
                <input id="email" type="email" class="form-input" placeholder="Enter Email" />
            </div>
            <button type="button" class="btn btn-primary w-full" (click)="router.navigate(['/'])">RECOVER</button>
        </form>
    </div>
</div>
