// src/UI/Vue/src/views/auth/sign-in.vue
<template>
    <div
        class="flex justify-center items-center min-h-screen bg-[url('/assets/images/map.svg')] dark:bg-[url('/assets/images/map-dark.svg')] bg-cover bg-center">
        <div class="panel sm:w-[480px] m-6 max-w-lg w-full">
            <h2 class="font-bold text-2xl mb-3">Sign In</h2>
            <p class="mb-7">Enter your email and password to login</p>
            <form class="space-y-5" @submit.prevent="router.push('/')">
                <div>
                    <label for="email">Email</label>
                    <input id="email" type="email" class="form-input" placeholder="Enter Email" />
                </div>
                <div>
                    <label for="password">Password</label>
                    <input id="password" type="password" class="form-input" placeholder="Enter Password" />
                </div>
                <div>
                    <label class="cursor-pointer">
                        <p class="text-left">
                            <router-link to="/auth/forgot-password"
                                class="text-primary font-bold hover:underline">Forgot Password</router-link>
                        </p>
                    </label>
                </div>
                <button type="submit" class="btn btn-primary w-full">SIGN IN</button>
            </form>

        </div>
    </div>
</template>
<script lang="ts" setup>
import { useRouter } from 'vue-router';
import { useMeta } from '@/composables/use-meta';
useMeta({ title: 'Login' });
const router = useRouter();
</script>

// src/UI/Angular/src/app/module/auth/pages/signin/signin.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-signin',
  templateUrl: './signin.component.html',
  styleUrl: './signin.component.css'
})
export class SigninComponent {
  constructor(public router: Router) {}

}

<div
  class="flex min-h-screen items-center justify-center bg-[url('/assets/images/map.svg')] bg-cover bg-center dark:bg-[url('/assets/images/map-dark.svg')]"
>
  <div class="panel m-6 w-full max-w-lg sm:w-[480px]">
    <h2 class="mb-3 text-2xl font-bold">Sign In</h2>
    <p class="mb-7">Enter your email and password to login</p>
    <form
      class="space-y-5"
      [formGroup]="formSignin"
      (ngSubmit)="submitFormSignin()"
      novalidate
    >
      <div>
        <label for="email">Email</label>
        <app-input
          formControlName="email"
          [control]="formSignin.controls['email']"
          [isSubmit]="isSubmitFormSignin"
          placeholder="Enter Email"
        ></app-input>
      </div>
      <div>
        <label for="password">Password</label>
        <app-input
          formControlName="password"
          type="password"
          [control]="formSignin.controls['password']"
          [isSubmit]="isSubmitFormSignin"
          placeholder="Enter Password"
        ></app-input>
      </div>
      <div>
        <app-anchor
          text="Forgot Password?"
          [routerLink]="forgotPasswordRoute"
          classes="font-bold text-primary"
        ></app-anchor>
      </div>
      <app-button
        text="SIGN IN"
        type="submit"
        classes="btn-primary w-full"
        class="d-block"
      ></app-button>
    </form>
    <div
      class="d-none relative my-7 h-5 text-center before:absolute before:inset-0 before:m-auto before:h-[1px] before:w-full before:bg-[#ebedf2] dark:before:bg-[#253b5c]"
    >
      <div
        class="relative z-[1] inline-block bg-white px-2 font-bold text-white-dark dark:bg-[#0e1726]"
      >
        <span>OR</span>
      </div>
    </div>
    <ul class="d-none mb-5 flex justify-center gap-2 sm:gap-5">
      <li>
        <button
          type="button"
          class="btn flex gap-1 bg-white-dark/30 text-black shadow-none hover:bg-white dark:border-[#253b5c] dark:bg-transparent dark:text-white dark:hover:bg-[#1b2e4b] sm:gap-2"
        >
          <svg
            class="h-5 w-5 shrink-0 sm:h-6 sm:w-6"
            viewBox="0 0 256 193"
            version="1.1"
            xmlns="http://www.w3.org/2000/svg"
            xmlns:xlink="http://www.w3.org/1999/xlink"
            preserveAspectRatio="xMidYMid"
          >
            <g>
              <path
                d="M58.1818182,192.049515 L58.1818182,93.1404244 L27.5066233,65.0770089 L0,49.5040608 L0,174.59497 C0,184.253152 7.82545455,192.049515 17.4545455,192.049515 L58.1818182,192.049515 Z"
                fill="#4285F4"
              ></path>
              <path
                d="M197.818182,192.049515 L238.545455,192.049515 C248.203636,192.049515 256,184.224061 256,174.59497 L256,49.5040608 L224.844415,67.3422767 L197.818182,93.1404244 L197.818182,192.049515 Z"
                fill="#34A853"
              ></path>
              <polygon
                fill="#EA4335"
                points="58.1818182 93.1404244 54.0077618 54.4932827 58.1818182 17.5040608 128 69.8676972 197.818182 17.5040608 202.487488 52.4960089 197.818182 93.1404244 128 145.504061"
              ></polygon>
              <path
                d="M197.818182,17.5040608 L197.818182,93.1404244 L256,49.5040608 L256,26.2313335 C256,4.64587897 231.36,-7.65957557 214.109091,5.28587897 L197.818182,17.5040608 Z"
                fill="#FBBC04"
              ></path>
              <path
                d="M0,49.5040608 L26.7588051,69.5731646 L58.1818182,93.1404244 L58.1818182,17.5040608 L41.8909091,5.28587897 C24.6109091,-7.65957557 0,4.64587897 0,26.2313335 L0,49.5040608 Z"
                fill="#C5221F"
              ></path>
            </g>
          </svg>
          Google
        </button>
      </li>
    </ul>
    <p class="d-none text-center">
      Dont't have an account ?
      <app-anchor
        text="Sign Up"
        classes="font-bold text-primary"
      ></app-anchor>
    </p>
  </div>
</div>
