// src/UI/Angular/src/app/module/auth/pages/reset-password/reset-password.component.ts
import { Component, inject } from '@angular/core';
import {
  AbstractControl,
  FormBuilder,
  FormGroup,
  FormsModule,
  ReactiveFormsModule,
  ValidatorFn,
  Validators,
} from '@angular/forms';
import { ActivatedRoute, Router, RouterModule } from '@angular/router';
import { AnchorComponent } from '../../../../shared/ui/anchor/anchor.component';
import { ButtonComponent } from '../../../../shared/ui/button/button.component';
import { InputComponent } from '../../../../shared/ui/input/input.component';
import { authPaths } from '../../../../shared/constants/routes';
import { IResetPasswordRequest } from '../../models/reset-password-request.interface';
import { AuthService } from '../../services/auth.service';
import { AlertService } from '../../../../shared/services/alert.service';
import {
  FieldValidation,
  Regex,
  queryStringParams,
} from '../../../../shared/constants/constants';
import { NgClass } from '@angular/common';

@Component({
  selector: 'app-reset-password',
  standalone: true,
  imports: [
    ReactiveFormsModule,
    InputComponent,
    ButtonComponent,
    AnchorComponent,
    NgClass,
  ],
  templateUrl: './reset-password.component.html',
  styleUrl: './reset-password.component.css',
})
export class ResetPasswordComponent {
  signinRoute = '/' + authPaths.signin;
  formResetPassword!: FormGroup;
  isSubmitFormResetPassword = false;
  forgotPasswordData!: IResetPasswordRequest;

  authService = inject(AuthService);
  alertService = inject(AlertService);
  router = inject(Router);
  fb = inject(FormBuilder);

  constructor(private route: ActivatedRoute) {
    this.initForm();
  }

  initForm() {
    this.formResetPassword = this.fb.group(
      {
        password: [
          '',
          Validators.compose([
            Validators.required,
            Validators.minLength(FieldValidation.passwordMinLength),
            Validators.pattern(Regex.passwordValidationPattern),
          ]),
        ],
        cpassword: [
          '',
          Validators.compose([
            Validators.required,
            Validators.minLength(FieldValidation.passwordMinLength),
            Validators.pattern(Regex.passwordValidationPattern),
          ]),
        ],
      },
      {
        validator: this.passwordMatchValidator,
      },
    );
  }

  passwordMatchValidator: ValidatorFn = (
    control: AbstractControl,
  ): { [key: string]: boolean } | null => {
    const password = control.get('password')?.value;
    const cpassword = control.get('cpassword')?.value;
    return password === cpassword ? null : { passwordMismatch: true };
  };

  submitFormResetPassword() {
    this.isSubmitFormResetPassword = true;
    if (this.formResetPassword.valid) {
      var email =
        this.route.snapshot.queryParamMap.get(queryStringParams.Email) ?? '';
      var token =
        this.route.snapshot.queryParamMap.get(queryStringParams.Token) ?? '';
      this.forgotPasswordData = {
        email: email,
        newPassword: this.formResetPassword.value.password,
        token: token,
      };
      this.authService.resetpassword(this.forgotPasswordData).subscribe(
        (res: any) => {
          this.isSubmitFormResetPassword = false;
          this.alertService.showMessage(res.data);
          this.formResetPassword.reset();
          this.router.navigate(['/' + authPaths.signin]);
        },
        (error) => {},
      );
    }
  }
}

<div
  class="flex min-h-screen items-center justify-center bg-[url('/assets/images/map.svg')] bg-cover bg-center dark:bg-[url('/assets/images/map-dark.svg')]"
>
  <div class="panel m-6 w-full max-w-lg sm:w-[480px]">
    <h2 class="mb-3 text-2xl font-bold">Set New Password</h2>
    <form
      class="space-y-5"
      [formGroup]="formResetPassword"
      (ngSubmit)="submitFormResetPassword()"
      novalidate
    >
      <div>
        <label for="password">Password</label>
        <app-input
          formControlName="password"
          type="password"
          [control]="formResetPassword.controls['password']"
          [isSubmit]="isSubmitFormResetPassword"
          placeholder="Enter Password"
        ></app-input>
      </div>
      <div
        [ngClass]="{
          'has-error':
            isSubmitFormResetPassword &&
            formResetPassword.errors?.['passwordMismatch'] &&
            formResetPassword.controls['cpassword'].value
        }"
      >
        <label for="password">Confirm Password</label>
        <app-input
          formControlName="cpassword"
          type="password"
          [control]="formResetPassword.controls['cpassword']"
          [isSubmit]="isSubmitFormResetPassword"
          placeholder="Enter Confirm Password"
        ></app-input>
        @if (
          isSubmitFormResetPassword &&
          formResetPassword.errors?.["passwordMismatch"] &&
          formResetPassword.controls["cpassword"].value
        ) {
          <p class="mt-1 text-danger">Passwords do not match.</p>
        }
      </div>
      <app-button
        text="RESET PASSWORD"
        type="submit"
        classes="btn-primary w-full"
        class="d-block"
      ></app-button>
    </form>
    <div
      style="margin-top: 1rem; margin-bottom: 1rem"
      class="relative h-5 text-center before:absolute before:inset-0 before:m-auto before:h-[1px] before:w-full before:bg-[#ebedf2] dark:before:bg-[#253b5c]"
    ></div>
    <p class="text-center">
      Back to
      <app-anchor
        text="Sign In"
        [routerLink]="signinRoute"
        classes="font-bold text-primary"
      ></app-anchor>
    </p>
  </div>
</div>

// src/UI/Vue/src/views/auth/reset-password.vue
<template>
    <div
        class="flex justify-center items-center min-h-screen bg-[url('/assets/images/map.svg')] dark:bg-[url('/assets/images/map-dark.svg')] bg-cover bg-center">
        <div class="panel sm:w-[480px] m-6 max-w-lg w-full">
            <h2 class="font-bold text-2xl mb-3">Set New Password</h2>
            <form class="space-y-5" @submit.prevent="submitForm()">
                <div :class="{ 'has-error': v$.password.$error }">
                    <label for="password">New Password</label>
                    <input id="password" type="password" placeholder="Enter New Password" class="form-input"
                        v-model="password" />
                    <template v-if="isSubmitForm && v$.password.$error">
                        <p class="text-danger mt-1">This can not be empty</p>
                    </template>
                </div>
                <div :class="{ 'has-error': v$.cpassword.$error }">
                    <label for="cpassword">Confirm Password</label>
                    <input id="cpassword" type="password" placeholder="Confirm New Password" class="form-input"
                        v-model="cpassword" />
                    <template v-if="isSubmitForm && v$.cpassword.required.$invalid">
                        <p class="text-danger mt-1">This can not be empty</p>
                    </template>
                    <template v-if="isSubmitForm && v$.cpassword.sameAsPassword.$invalid">
                        <p class="text-danger mt-1">Password do not match</p>
                    </template>
                </div>
                <button type="submit" class="btn btn-primary w-full">RESET PASSWORD</button>
                <div
                    class="relative my-7 h-5 text-center before:w-full before:h-[1px] before:absolute before:inset-0 before:m-auto before:bg-[#ebedf2] dark:before:bg-[#253b5c]">
                    <div class="font-bold text-white-dark bg-white dark:bg-[#0e1726] px-2 relative z-[1] inline-block">
                        <span>OR</span>
                    </div>
                </div>
                <p class="text-center">
                    Go to <router-link :to="signinRoute" class="text-primary font-bold hover:underline">Sign
                        In</router-link>
                </p>
            </form>
        </div>
    </div>
</template>
<script lang="ts">
import { resetPasswordApi } from '../../common/api-paths';
import { useVuelidate } from '@vuelidate/core'
import { required } from '@vuelidate/validators'
import { useMeta } from '@/composables/use-meta';
import api from '@/services/api';
import messageService from '@/services/message.service';
import type { IResetPasswordRequest } from '@/types/reset-password';
import { signin } from '../../common/route-paths';

useMeta({ title: 'Reset Password' });

export default {
    setup() {
        return {
            v$: useVuelidate()
        }
    },
    data() {
        return {
            signinRoute: signin,
            isSubmitForm: false,
            password: '',
            cpassword: '',
        }
    },
    validations() {
        return {
            password: {
                required: required,
            },
            cpassword: {
                required: required,
                sameAsPassword: (value: any, vm: any) => value === vm.password,
            },
        }
    }, methods: {
        async submitForm() {
            this.isSubmitForm = true

            const isFormCorrect = await this.v$.$validate()
            if (!isFormCorrect) return
            const response = await api
                .post(resetPasswordApi, {
                    token: this.$route.query.token,
                    email: this.$route.query.email,
                    newPassword: this.password
                } as IResetPasswordRequest);
            if (response.data) {
                messageService.showMessage(response.data.data);
                this.$router.push(this.signinRoute);
            }
        }
    }
}
</script>
