// src/UI/React/src/pages/auth/sign-in.tsx
import { Link, useNavigate } from "react-router-dom";
import { useDispatch } from "react-redux";
import { useEffect } from "react";
import { setPageTitle } from "../../store/themeConfigSlice";

const LoginBoxed = () => {
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(setPageTitle("Sign In"));
  });
  const navigate = useNavigate();

  const submitForm = () => {
    navigate("/");
  };

  return (
    <div className="flex justify-center items-center min-h-screen bg-cover bg-center bg-[url('/assets/images/map.svg')] dark:bg-[url('/assets/images/map-dark.svg')]">
      <div className="panel sm:w-[480px] m-6 max-w-lg w-full">
        <h2 className="font-bold text-2xl mb-3">Sign In</h2>
        <p className="mb-7">Enter your email and password to login</p>
        <form className="space-y-5" onSubmit={submitForm}>
          <div>
            <label htmlFor="email">Email</label>
            <input
              id="email"
              type="email"
              className="form-input"
              placeholder="Enter Email"
            />
          </div>
          <div>
            <label htmlFor="password">Password</label>
            <input
              id="password"
              type="password"
              className="form-input"
              placeholder="Enter Password"
            />
          </div>
          <div>
            <label className="cursor-pointer">
              <Link
                to="/forgot-password"
                className="font-bold text-primary hover:underline ltr:ml-1 rtl:mr-1"
              >
                Forgot password
              </Link>
            </label>
          </div>
          <button type="submit" className="btn btn-primary w-full">
            SIGN IN
          </button>
        </form>
      </div>
    </div>
  );
};

export default LoginBoxed;

// src/UI/Vue/src/views/auth/sign-in.vue
<template>
    <div
        class="flex justify-center items-center min-h-screen bg-[url('/assets/images/map.svg')] dark:bg-[url('/assets/images/map-dark.svg')] bg-cover bg-center">
        <div class="panel sm:w-[480px] m-6 max-w-lg w-full">
            <h2 class="font-bold text-2xl mb-3">Sign In</h2>
            <p class="mb-7">Enter your email and password to login</p>
            <form class="space-y-5" @submit.prevent="router.push('/')">
                <div>
                    <label for="email">Email</label>
                    <input id="email" type="email" class="form-input" placeholder="Enter Email" />
                </div>
                <div>
                    <label for="password">Password</label>
                    <input id="password" type="password" class="form-input" placeholder="Enter Password" />
                </div>
                <div>
                    <label class="cursor-pointer">
                        <p class="text-left">
                            <router-link to="/auth/forgot-password"
                                class="text-primary font-bold hover:underline">Forgot Password</router-link>
                        </p>
                    </label>
                </div>
                <button type="submit" class="btn btn-primary w-full">SIGN IN</button>
            </form>

        </div>
    </div>
</template>
<script lang="ts" setup>
import { useRouter } from 'vue-router';
import { useMeta } from '@/composables/use-meta';
useMeta({ title: 'Login' });
const router = useRouter();
</script>
