// src/UI/React/src/pages/auth/pages/sign-in.tsx
import { Link, useNavigate } from "react-router-dom";
import { useDispatch } from "react-redux";
import { useEffect } from "react";
import { setPageTitle } from "../../../store/themeConfigSlice";
import { Field, Form, Formik } from "formik";
import * as Yup from "yup";
import authService from "../utils/auth.service";
import { pageTitle } from "../../../utils/common/route-paths";

const SignIn = () => {
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(setPageTitle(pageTitle.signin));
  });
  const navigate = useNavigate();

  const submitForm = (values: any) => {
    const { email, password } = values;

    const promise = authService.login(email, password);

    promise.then(() => {
      navigate("/");
    });
  };

  const SubmittedForm = Yup.object().shape({
    email: Yup.string().required("This can not be empty"),
    password: Yup.string().required("This can not be empty"),
  });

  return (
    <div className="flex justify-center items-center min-h-screen bg-cover bg-center bg-[url('/assets/images/map.svg')] dark:bg-[url('/assets/images/map-dark.svg')]">
      <div className="panel sm:w-[480px] m-6 max-w-lg w-full">
        <h2 className="font-bold text-2xl mb-3">Sign In</h2>
        <p className="mb-7">Enter your email and password to login</p>
        <Formik
          initialValues={{
            email: "",
            password: "",
          }}
          validationSchema={SubmittedForm}
          onSubmit={() => {}}
        >
          {({ errors, submitCount, isValid, values }) => (
            <Form className="space-y-5">
              <div
                className={submitCount ? (errors.email ? "has-error" : "") : ""}
              >
                <label htmlFor="email">Email</label>
                <Field
                  name="email"
                  type="text"
                  id="email"
                  placeholder="Enter Email"
                  className="form-input"
                />
                {submitCount ? (
                  errors.email ? (
                    <div className="text-danger mt-1">{errors.email}</div>
                  ) : (
                    ""
                  )
                ) : (
                  ""
                )}
              </div>
              <div
                className={
                  submitCount ? (errors.password ? "has-error" : "") : ""
                }
              >
                <label htmlFor="password">Password</label>
                <Field
                  name="password"
                  type="password"
                  id="password"
                  placeholder="Enter Password"
                  className="form-input"
                />
                {submitCount ? (
                  errors.password ? (
                    <div className="text-danger mt-1">{errors.password}</div>
                  ) : (
                    ""
                  )
                ) : (
                  ""
                )}
              </div>
              <div>
                <label className="cursor-pointer">
                  <Link
                    to="/forgot-password"
                    className="font-bold text-primary hover:underline ltr:ml-1 rtl:mr-1"
                  >
                    Forgot password
                  </Link>
                </label>
              </div>
              <button
                type="submit"
                className="btn btn-primary w-full"
                onClick={() => {
                  if (isValid && values.email && values.password) {
                    submitForm(values);
                  }
                }}
              >
                SIGN IN
              </button>
            </Form>
          )}
        </Formik>
      </div>
    </div>
  );
};

export default SignIn;

// src/UI/Vue/src/views/auth/sign-in.vue
<template>
    <div
        class="flex justify-center items-center min-h-screen bg-[url('/assets/images/map.svg')] dark:bg-[url('/assets/images/map-dark.svg')] bg-cover bg-center">
        <div class="panel sm:w-[480px] m-6 max-w-lg w-full">
            <h2 class="font-bold text-2xl mb-3">Sign In</h2>
            <p class="mb-7">Enter your email and password to login</p>
            <form class="space-y-5" @submit.prevent="submitForm()">
                <div :class="{ 'has-error': v$.email.$error }">
                    <label for="email">Email</label>
                    <input id="email" type="text" placeholder="Enter Email" class="form-input" v-model="email" />
                    <template v-if="isSubmitForm && v$.email.$error">
                        <p class="text-danger mt-1">This can not be empty</p>
                    </template>
                </div>
                <div :class="{ 'has-error': v$.password.$error }">
                    <label for="password">Password</label>
                    <input id="password" type="password" placeholder="Enter Password" class="form-input"
                        v-model="password" />
                    <template v-if="isSubmitForm && v$.password.$error">
                        <p class="text-danger mt-1">This can not be empty</p>
                    </template>
                </div>
                <div>
                    <router-link :to="forgotPasswordRoute" class="text-primary font-bold hover:underline">Forgot
                        Password</router-link>
                </div>
                <button type="submit" class="btn btn-primary w-full">SIGN IN</button>
            </form>
        </div>
    </div>
</template>
<script lang="ts">
import { useVuelidate } from '@vuelidate/core'
import { required } from '@vuelidate/validators'
import authService from '@/services/auth.service';
import { useMeta } from '@/composables/use-meta';
import { forgotPassword } from '../../common/route-paths';

useMeta({ title: 'Login' });

export default {
    setup() {
        return {
            v$: useVuelidate()
        }
    },
    data() {
        return {
            forgotPasswordRoute: forgotPassword,
            isSubmitForm: false,
            email: '',
            password: ''
        }
    },
    validations() {
        return {
            email: { required },
            password: { required }
        }
    }, methods: {
        async submitForm() {
            this.isSubmitForm = true

            const isFormCorrect = await this.v$.$validate()
            if (!isFormCorrect) return

            const promise = authService.login({ email: this.email, password: this.password });

            promise.then(rs => {
                this.$router.push("/");
            });
        }
    }
}
</script>
