// src/UI/React/src/pages/user/pages/profile.tsx
import { useEffect, useState } from "react";
import { useDispatch } from "react-redux";
import { setPageTitle } from "../../../store/themeConfigSlice";
import { pageTitle } from "../../../utils/common/route-paths";
import axiosInstance from "../../../utils/api.service";
import { APIs } from "../../../utils/common/api-paths";
import { Field, Form, Formik } from "formik";
import * as Yup from "yup";
import messageService from "../../../utils/message.service";
import { updateUserInfo } from "../../../store/userInfoSlice";
import LocalStorageService from "../../../utils/localstorage.service";

const localStorageService = LocalStorageService.getService();

const Profile = () => {
  const dispatch = useDispatch();

  const [profileDetails, setProfileDetails] = useState<{
    id: string;
    firstName: string;
    lastName: string;
    email: string;
  }>({
    id: "",
    firstName: "",
    lastName: "",
    email: "",
  });

  useEffect(() => {
    dispatch(setPageTitle(pageTitle.profile));

    const fetchProfileDetails = async () => {
      const response = await axiosInstance.get(APIs.getProfileDetails);
      if (response.data)
        setProfileDetails({
          id: response.data.data.id,
          firstName: response.data.data.firstName,
          lastName: response.data.data.lastName,
          email: response.data.data.email,
        });
    };

    fetchProfileDetails();
  }, [dispatch]);

  const submitForm = async (values: any) => {
    const response = await axiosInstance.put(
      APIs.updateProfile + values.id,
      values
    );

    if (response.data) {
      dispatch(
        updateUserInfo({
          fullName: values.firstName + " " + values.lastName,
          email: values.email,
        })
      );
      localStorageService.updateStorageUserInfo(
        values.firstName + " " + values.lastName,
        values.email
      );
      messageService.showMessage(response.data.data);
    }
  };

  const SubmittedForm = Yup.object().shape({
    firstName: Yup.string().required("This can not be empty"),
    lastName: Yup.string().required("This can not be empty"),
    email: Yup.string()
      .email("Invalid email")
      .required("This can not be empty"),
  });

  return (
    <div className="pt-5">
      <Formik
        enableReinitialize={true}
        initialValues={{
          id: profileDetails.id,
          firstName: profileDetails.firstName,
          lastName: profileDetails.lastName,
          email: profileDetails.email,
        }}
        validationSchema={SubmittedForm}
        onSubmit={() => {}}
      >
        {({ errors, submitCount, values }) => (
          <Form className="border border-[#ebedf2] dark:border-[#191e3a] rounded-md p-4 mb-5 bg-white dark:bg-black">
            <h6 className="text-lg font-bold mb-5">My Profile</h6>
            <div className="flex flex-col sm:flex-row">
              <div className="ltr:sm:mr-4 rtl:sm:ml-4 w-full sm:w-2/12 mb-5">
                <img
                  src="/assets//images/default_profile.png"
                  alt="img"
                  className="w-20 h-20 md:w-32 md:h-32 rounded-full object-cover mx-auto"
                />
              </div>

              <div className="flex-1 grid grid-cols-1 sm:grid-cols-2 gap-5">
                <div
                  className={
                    submitCount ? (errors.firstName ? "has-error" : "") : ""
                  }
                >
                  <label htmlFor="firstName">First Name</label>
                  <Field
                    name="firstName"
                    type="text"
                    id="firstName"
                    placeholder="Enter First Name"
                    className="form-input"
                  />
                  {submitCount ? (
                    errors.firstName ? (
                      <div className="text-danger mt-1">{errors.firstName}</div>
                    ) : (
                      ""
                    )
                  ) : (
                    ""
                  )}
                </div>
                <div
                  className={
                    submitCount ? (errors.lastName ? "has-error" : "") : ""
                  }
                >
                  <label htmlFor="lastName">Last Name</label>
                  <Field
                    name="lastName"
                    type="text"
                    id="lastName"
                    placeholder="Enter Last Name"
                    className="form-input"
                  />
                  {submitCount ? (
                    errors.lastName ? (
                      <div className="text-danger mt-1">{errors.lastName}</div>
                    ) : (
                      ""
                    )
                  ) : (
                    ""
                  )}
                </div>
                <div
                  className={
                    submitCount ? (errors.email ? "has-error" : "") : ""
                  }
                >
                  <label htmlFor="email">Email</label>
                  <Field
                    name="email"
                    type="text"
                    id="email"
                    placeholder="Enter Email"
                    className="form-input  disabled-textbox"
                    disabled
                  />
                  {submitCount ? (
                    errors.email ? (
                      <div className="text-danger mt-1">{errors.email}</div>
                    ) : (
                      ""
                    )
                  ) : (
                    ""
                  )}
                </div>
                <div className="sm:col-span-2 mt-3">
                  <button
                    type="submit"
                    className="btn btn-primary"
                    onClick={() => {
                      if (Object.keys(errors).length === 0) {
                        submitForm(values);
                      }
                    }}
                  >
                    Save
                  </button>
                </div>
              </div>
            </div>
          </Form>
        )}
      </Formik>
    </div>
  );
};

export default Profile;

// src/UI/Vue/src/views/apps/user/profile.vue
<!-- eslint-disable vue/multi-word-component-names -->
<template>
    <div>
        <div class="pt-5">
            <div>
                <form @submit.prevent="submitForm()"
                    class="border border-[#ebedf2] dark:border-[#191e3a] rounded-md p-4 mb-5 bg-white dark:bg-[#0e1726]">
                    <h6 class="text-lg font-bold mb-5">My Profile</h6>
                    <div class="flex flex-col sm:flex-row">
                        <div class="ltr:sm:mr-4 rtl:sm:ml-4 w-full sm:w-2/12 mb-5">
                            <img src="@/assets/images/default_profile.png" alt=""
                                class="w-20 h-20 md:w-32 md:h-32 rounded-full object-cover mx-auto" />
                        </div>
                        <div class="flex-1 grid grid-cols-1 sm:grid-cols-2 gap-5">
                            <div :class="{ 'has-error': v$.params.firstName.$error }">
                                <label for="firstName">First Name</label>
                                <input id="firstName" type="text" placeholder="Enter First Name" class="form-input"
                                    v-model="params.firstName" />
                                <template v-if="isSubmitForm && v$.params.firstName.$error">
                                    <p class="text-danger mt-1" v-for="error of v$.params.firstName.$errors"
                                        :key="error.$uid">
                                        <span v-if="error.$validator == 'required'">This can not be empty</span>
                                        <span v-if="error.$validator == 'noSpace'">Invalid First Name</span>
                                    </p>
                                </template>
                            </div>
                            <div :class="{ 'has-error': v$.params.lastName.$error }">
                                <label for="lastName">Last Name</label>
                                <input id="lastName" type="text" placeholder="Enter Last Name" class="form-input"
                                    v-model="params.lastName" />
                                <template v-if="isSubmitForm && v$.params.lastName.$error">
                                    <p class="text-danger mt-1" v-for="error of v$.params.lastName.$errors"
                                        :key="error.$uid">
                                        <span v-if="error.$validator == 'required'">This can not be empty</span>
                                        <span v-if="error.$validator == 'noSpace'">Invalid Last Name</span>
                                    </p>
                                </template>
                            </div>
                            <div>
                                <label for="address">Email</label>
                                <input id="address" type="text" placeholder="New York" class="form-input disabled-textbox"
                                    v-model="params.email" disabled />
                            </div>
                            <div class="sm:col-span-2 mt-3">
                                <button type="submit" class="btn btn-primary" :disabled="isSaveDisabled">Save</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</template>
<script lang="ts">
import { updateProfile, getProfileDetails } from '@/common/api-paths';
import { noSpaceValidationPattern } from '@/common/constants';
import { useMeta } from '@/composables/use-meta';
import api from '@/services/api';
import messageService from '@/services/message.service';
import tokenService from '@/services/token.service';
import useVuelidate from '@vuelidate/core';
import { required } from '@vuelidate/validators';
import { useStore } from 'vuex'

useMeta({ title: 'Profile Information' });

export default {
    setup() {
        return {
            v$: useVuelidate(),
            $store: useStore()
        }
    },
    data() {
        return {
            isSaveDisabled: false,
            isSubmitForm: false,
            params: { id: '', firstName: '', lastName: '', email: '', },
            originalParams: { id: '', firstName: '', lastName: '', email: '', },
        }
    },
    validations() {
        return {
            params: {
                firstName: { required, noSpace: value => noSpaceValidationPattern.test(value), },
                lastName: { required, noSpace: value => noSpaceValidationPattern.test(value), },
            },
        }
    },
    created() {
        this.setUserDetails();
    },
    watch: {
        params: {
            deep: true,
            handler(newParams) {
                this.isSaveDisabled = this.isParamsUnchanged(newParams);
            },
        },
    },
    methods: {
        async submitForm() {
            this.isSubmitForm = true
            const isFormCorrect = await this.v$.$validate()
            if (!isFormCorrect) return

            const response = await api
                .put(updateProfile + this.params.id, this.params)
                ;

            if (response.data) {
                this.originalParams = { ...this.params }
                this.isSaveDisabled = true
                this.$store.commit('updateProfileInfo', {
                    fullName: this.params.firstName + ' ' + this.params.lastName,
                    email: this.params.email,
                })
                tokenService.updateStorageUserInfo(
                    this.params.firstName + ' ' + this.params.lastName,
                    this.params.email,
                );
                messageService.showMessage(response.data.data);
            }
        },
        async setUserDetails() {
            const response = await api
                .get(getProfileDetails);
            if (response.data) {
                this.originalParams = { id: response.data.data.id, firstName: response.data.data.firstName, lastName: response.data.data.lastName, email: response.data.data.email }
                this.params = { id: response.data.data.id, firstName: response.data.data.firstName, lastName: response.data.data.lastName, email: response.data.data.email }
            }
        },
        isParamsUnchanged(newParams) {
            return JSON.stringify(newParams) == JSON.stringify(this.originalParams);
        },
    }
};
</script>
