// src/UI/Vue/src/views/auth/reset-password.vue
<template>
    <div
        class="flex justify-center items-center min-h-screen bg-[url('/assets/images/map.svg')] dark:bg-[url('/assets/images/map-dark.svg')] bg-cover bg-center">
        <div class="panel sm:w-[480px] m-6 max-w-lg w-full">
            <h2 class="font-bold text-2xl mb-3">Set New Password</h2>
            <form class="space-y-5" @submit.prevent="submitForm()">
                <span class="text-white-dark text-xs">Password requirements: At least one uppercase
                    letter (A-Z), one lowercase
                    letter (a-z), and one non-alphanumeric character.</span>
                <div :class="{ 'has-error': v$.password.$error }">
                    <label for="password">New Password</label>
                    <input id="password" type="password" placeholder="Enter New Password" class="form-input"
                        v-model="password" />
                    <template v-if="isSubmitForm && v$.password.$error">
                        <p class="text-danger mt-1" v-for="error of v$.password.$errors" :key="error.$uid">
                            <span v-if="error.$validator == 'required'">This can not be empty</span>
                            <span v-if="error.$validator == 'minLength'">Minimum length should be {{
                                v$.password.minLength.$params.min }} characters</span>
                            <span v-if="error.$validator == 'passPatern'">Password requirements: At least one uppercase
                                letter (A-Z), one lowercase
                                letter (a-z), and one non-alphanumeric character.</span>
                        </p>
                    </template>
                </div>
                <div :class="{ 'has-error': v$.cpassword.$error }">
                    <label for="cpassword">Confirm Password</label>
                    <input id="cpassword" type="password" placeholder="Confirm New Password" class="form-input"
                        v-model="cpassword" />
                    <template v-if="isSubmitForm && v$.cpassword.required.$invalid">
                        <p class="text-danger mt-1">This can not be empty</p>
                    </template>
                    <template v-if="isSubmitForm && v$.cpassword.minLength.$invalid">
                        <p class="text-danger mt-1">Minimum length should be {{
                            v$.cpassword.minLength.$params.min }} characters</p>
                    </template>
                    <template v-if="isSubmitForm && v$.cpassword.passPatern.$invalid">
                        <p class="text-danger mt-1">Password requirements: At least one uppercase
                            letter (A-Z), one lowercase
                            letter (a-z), and one non-alphanumeric character.</p>
                    </template>
                    <template v-if="isSubmitForm && v$.cpassword.sameAsPassword.$invalid">
                        <p class="text-danger mt-1">Password do not match</p>
                    </template>
                </div>
                <button type="submit" class="btn btn-primary w-full">RESET PASSWORD</button>
                <div
                    class="relative my-7 h-5 text-center before:w-full before:h-[1px] before:absolute before:inset-0 before:m-auto before:bg-[#ebedf2] dark:before:bg-[#253b5c]">
                    <div class="font-bold text-white-dark bg-white dark:bg-[#0e1726] px-2 relative z-[1] inline-block">
                        <span>OR</span>
                    </div>
                </div>
                <p class="text-center">
                    Go to <router-link :to="signinRoute" class="text-primary font-bold hover:underline">Sign
                        In</router-link>
                </p>
            </form>
        </div>
    </div>
</template>
<script lang="ts">
import { resetPasswordApi } from '../../common/api-paths';
import { useVuelidate } from '@vuelidate/core'
import { minLength, required } from '@vuelidate/validators'
import { useMeta } from '@/composables/use-meta';
import api from '@/services/api';
import messageService from '@/services/message.service';
import type { IResetPasswordRequest } from '@/types/reset-password';
import { signin } from '../../common/route-paths';
import { passwordValidationPattern } from '@/common/constants';

useMeta({ title: 'Reset Password' });

export default {
    setup() {
        return {
            v$: useVuelidate()
        }
    },
    data() {
        return {
            signinRoute: signin,
            isSubmitForm: false,
            password: '',
            cpassword: '',
        }
    },
    validations() {
        return {
            password: { required, minLength: minLength(6), passPatern: value => passwordValidationPattern.test(value), },
            cpassword: {
                required: required,
                minLength: minLength(6),
                passPatern: value => passwordValidationPattern.test(value),
                sameAsPassword: (value: any, vm: any) => value === vm.password,
            },
        }
    }, methods: {
        async submitForm() {
            this.isSubmitForm = true

            const isFormCorrect = await this.v$.$validate()
            if (!isFormCorrect) return
            const response = await api
                .post(resetPasswordApi, {
                    token: this.$route.query.token,
                    email: this.$route.query.email,
                    newPassword: this.password
                } as IResetPasswordRequest);
            if (response.data) {
                messageService.showMessage(response.data.data);
                this.$router.push(this.signinRoute);
            }
        }
    }
}
</script>

// src/UI/React/src/pages/auth/pages/reset-password.tsx
import { Link, useNavigate } from "react-router-dom";
import { useDispatch } from "react-redux";
import { useEffect } from "react";
import { setPageTitle } from "../../../store/themeConfigSlice";
import { authPaths, pageTitle } from "../../../utils/common/route-paths";
import { Field, Form, Formik } from "formik";
import * as Yup from "yup";
import { APIs } from "../../../utils/common/api-paths";
import messageService from "../../../utils/message.service";
import axiosInstance from "../../../utils/api.service";
import { useLocation } from "react-router-dom";
import { Regex } from "../../../utils/common/constants";

const ResetPassword = () => {
  const location = useLocation();
  const dispatch = useDispatch();
  const navigate = useNavigate();

  useEffect(() => {
    dispatch(setPageTitle(pageTitle.forgotPassword));
  });

  const submitForm = async (values: any) => {
    const queryParams = new URLSearchParams(location.search);
    const token = queryParams.get("token");
    const email = queryParams.get("email");

    const response = await axiosInstance.post(APIs.resetPasswordApi, {
      token: token,
      email: email,
      newPassword: values.password,
    });
    if (response.data) {
      messageService.showMessage(response.data.data);
      navigate("/" + authPaths.signin);
    }
  };

  const SubmittedForm = Yup.object().shape({
    password: Yup.string()
      .required("This can not be empty")
      .min(6, "Confirm password must be at least 6 characters")
      .matches(
        Regex.passwordValidationPattern,
        "Password requirements: At least one uppercase letter (A-Z), one lowercase letter (a-z), and one non-alphanumeric character."
      ),
    cpassword: Yup.string()
      .required("This can not be empty")
      .oneOf([Yup.ref("password"), ""], "Password must match"),
  });

  return (
    <div className="flex justify-center items-center min-h-screen bg-cover bg-center bg-[url('/assets/images/map.svg')] dark:bg-[url('/assets/images/map-dark.svg')]">
      <div className="panel sm:w-[480px] m-6 max-w-lg w-full">
        <h2 className="font-bold text-2xl mb-3">Set New Password</h2>
        <Formik
          initialValues={{
            password: "",
            cpassword: "",
          }}
          validationSchema={SubmittedForm}
          onSubmit={() => {}}
        >
          {({ errors, submitCount, touched, values }) => (
            <Form className="space-y-5">
              <span className="text-white-dark text-xs">
                Password requirements: At least one uppercase letter (A-Z), one
                lowercase letter (a-z), and one non-alphanumeric character.
              </span>
              <div
                className={
                  submitCount ? (errors.password ? "has-error" : "") : ""
                }
              >
                <label htmlFor="password">New Password </label>
                <Field
                  name="password"
                  type="password"
                  id="password"
                  placeholder="Enter New Password"
                  className="form-input"
                />

                {submitCount ? (
                  errors.password ? (
                    <div className="text-danger mt-1">{errors.password}</div>
                  ) : (
                    ""
                  )
                ) : (
                  ""
                )}
              </div>
              <div
                className={
                  submitCount ? (errors.cpassword ? "has-error" : "") : ""
                }
              >
                <label htmlFor="cpassword">Confirm Password </label>
                <Field
                  name="cpassword"
                  type="password"
                  id="cpassword"
                  placeholder="Confirm New Password"
                  className="form-input"
                />

                {submitCount ? (
                  errors.cpassword ? (
                    <div className="text-danger mt-1">{errors.cpassword}</div>
                  ) : (
                    ""
                  )
                ) : (
                  ""
                )}
              </div>
              <button
                type="submit"
                className="btn btn-primary w-full"
                onClick={() => {
                  if (
                    touched.password &&
                    !errors.password &&
                    touched.cpassword &&
                    !errors.cpassword
                  ) {
                    submitForm(values);
                  }
                }}
              >
                RESET PASSWORD
              </button>
            </Form>
          )}
        </Formik>
        <div className="relative my-7 h-5 text-center before:w-full before:h-[1px] before:absolute before:inset-0 before:m-auto before:bg-[#ebedf2] dark:before:bg-[#253b5c]">
          <div className="font-bold text-white-dark bg-white dark:bg-black px-2 relative z-[1] inline-block">
            <span>OR</span>
          </div>
        </div>
        <p className="text-center">
          Go To
          <Link
            to={"/" + authPaths.signin}
            className="font-bold text-primary hover:underline ltr:ml-1 rtl:mr-1"
          >
            Sign In
          </Link>
        </p>
      </div>
    </div>
  );
};

export default ResetPassword;
