// src/UI/React/src/pages/project/pages/list-projects.tsx
import { DataTable, DataTableSortStatus } from "mantine-datatable";
import { useEffect, useState } from "react";
import Tippy from "@tippyjs/react";
import "tippy.js/dist/tippy.css";
import { useDispatch } from "react-redux";
import { setPageTitle } from "../../../store/themeConfigSlice";
import axiosInstance from "../../../utils/api.service";
import { APIs } from "../../../utils/common/api-paths";
import { PaginationFilter } from "../../../utils/types/pagination-filter.interface";
import filterService from "../../../utils/filter.service";
import { dataTableProps } from "../../../utils/common/constants";
import { pageTitle } from "../../../utils/common/route-paths";
import DeleteProjectModal from "../../../components/Shared/delete-modal";
import messageService from "../../../utils/message.service";
import ManageProjectModal from "../components/manage-project";

const Projects = () => {
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(setPageTitle(pageTitle.projects));
  });

  const PAGE_SIZES = dataTableProps.PAGE_SIZES;
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(PAGE_SIZES[0]);
  const [recordsData, setRecordsData] = useState({ data: [], all_counts: 0 });
  const [params, setParams] = useState(filterService.defaultFilter());
  const [sortStatus, setSortStatus] = useState<DataTableSortStatus>({
    columnAccessor: "projectName",
    direction: "asc",
  });
  const [isdeleteProjectModal, setIsDeleteProjectModal] = useState<any>(false);
  const [deletedProjectId, setdeletedProjectId] = useState<string>("");
  const [isManageProjectModal, setIsManageProjectModal] = useState<any>(false);
  const [managedProjectId, setManagedProjectId] = useState<string>("");

  useEffect(() => {
    setParams({
      PageNumber: page,
      PageSize: pageSize,
      OrderBy: [
        getSortColumnName(sortStatus.columnAccessor) +
          " " +
          sortStatus.direction,
      ],
    });
  }, [sortStatus, page, pageSize]);

  useEffect(() => {
    bindProjects(params);
  }, [params]);

  const bindProjects = async (params: PaginationFilter) => {
    const response = await axiosInstance.post(APIs.searchProjectsApi, params);
    if (response.data) {
      setRecordsData({
        data: response.data.data,
        all_counts: response.data.totalCount,
      });
    }
  };

  const deleteProjectConfirm = (id: string) => {
    setdeletedProjectId(id);
    setIsDeleteProjectModal(true);
  };

  const deleteProject = async () => {
    const response = await axiosInstance.delete(
      APIs.deleteProjectApi + deletedProjectId
    );
    if (response.data) {
      messageService.showMessage(response.data.message);
      bindProjects(params);
      setIsDeleteProjectModal(false);
    }
  };

  const manageProjectConfirm = (id: string) => {
    setManagedProjectId(id);
    setTimeout(() => {
      setIsManageProjectModal(true);
    }, 100);
  };

  const onSaveManageProject = async () => {
    setManagedProjectId("");
    bindProjects(params);
    setIsManageProjectModal(false);
  };

  const onCloseManageProject = async () => {
    setManagedProjectId("");
    setIsManageProjectModal(false);
  };

  const getSortColumnName = (column: string) => {
    switch (column) {
      case "startDateDisplay":
        return "startDate";
      case "endDateDisplay":
        return "endDate";
      default:
        return column;
    }
  };

  return (
    <div className="panel">
      <div className="flex md:items-center md:flex-row flex-col mb-5 gap-5">
        <h5 className="font-semibold text-lg dark:text-white-light">
          Projects
        </h5>
        <div className="ltr:ml-auto rtl:mr-auto">
          <button
            type="button"
            className="btn btn-outline-info btn-sm"
            onClick={() => setIsManageProjectModal(true)}
          >
            Add
          </button>
        </div>
      </div>
      <div className="datatables">
        <DataTable
          highlightOnHover
          className="whitespace-nowrap table-hover"
          records={recordsData.data}
          columns={[
            { accessor: "projectName", title: "Project Name", sortable: true },
            {
              accessor: "startDateDisplay",
              title: "Start Date",
              sortable: true,
            },
            { accessor: "endDateDisplay", title: "End Date", sortable: true },
            {
              accessor: "estimatedHours",
              title: "Estimated Hours",
              sortable: true,
            },
            {
              accessor: "action",
              title: "Action",
              titleClassName: "!text-center",
              render: ({ id }) => (
                <div className="flex items-center w-max mx-auto gap-2">
                  <Tippy content="Edit">
                    <button
                      type="button"
                      onClick={() => manageProjectConfirm(id)}
                    >
                      <svg
                        width="24"
                        height="24"
                        viewBox="0 0 24 24"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                        className="w-5 h-5 text-success"
                      >
                        <path
                          d="M15.2869 3.15178L14.3601 4.07866L5.83882 12.5999L5.83881 12.5999C5.26166 13.1771 4.97308 13.4656 4.7249 13.7838C4.43213 14.1592 4.18114 14.5653 3.97634 14.995C3.80273 15.3593 3.67368 15.7465 3.41556 16.5208L2.32181 19.8021L2.05445 20.6042C1.92743 20.9852 2.0266 21.4053 2.31063 21.6894C2.59466 21.9734 3.01478 22.0726 3.39584 21.9456L4.19792 21.6782L7.47918 20.5844L7.47919 20.5844C8.25353 20.3263 8.6407 20.1973 9.00498 20.0237C9.43469 19.8189 9.84082 19.5679 10.2162 19.2751C10.5344 19.0269 10.8229 18.7383 11.4001 18.1612L11.4001 18.1612L19.9213 9.63993L20.8482 8.71306C22.3839 7.17735 22.3839 4.68748 20.8482 3.15178C19.3125 1.61607 16.8226 1.61607 15.2869 3.15178Z"
                          stroke="currentColor"
                          strokeWidth="1.5"
                        />
                        <path
                          opacity="0.5"
                          d="M14.36 4.07812C14.36 4.07812 14.4759 6.04774 16.2138 7.78564C17.9517 9.52354 19.9213 9.6394 19.9213 9.6394M4.19789 21.6777L2.32178 19.8015"
                          stroke="currentColor"
                          strokeWidth="1.5"
                        />
                      </svg>
                    </button>
                  </Tippy>
                  <Tippy content="Delete">
                    <button
                      type="button"
                      onClick={() => deleteProjectConfirm(id)}
                    >
                      <svg
                        className="text-danger"
                        width="20"
                        height="20"
                        viewBox="0 0 24 24"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          opacity="0.5"
                          d="M9.17065 4C9.58249 2.83481 10.6937 2 11.9999 2C13.3062 2 14.4174 2.83481 14.8292 4"
                          stroke="currentColor"
                          strokeWidth="1.5"
                          strokeLinecap="round"
                        />
                        <path
                          d="M20.5001 6H3.5"
                          stroke="currentColor"
                          strokeWidth="1.5"
                          strokeLinecap="round"
                        />
                        <path
                          d="M18.8334 8.5L18.3735 15.3991C18.1965 18.054 18.108 19.3815 17.243 20.1907C16.378 21 15.0476 21 12.3868 21H11.6134C8.9526 21 7.6222 21 6.75719 20.1907C5.89218 19.3815 5.80368 18.054 5.62669 15.3991L5.16675 8.5"
                          stroke="currentColor"
                          strokeWidth="1.5"
                          strokeLinecap="round"
                        />
                        <path
                          opacity="0.5"
                          d="M9.5 11L10 16"
                          stroke="currentColor"
                          strokeWidth="1.5"
                          strokeLinecap="round"
                        />
                        <path
                          opacity="0.5"
                          d="M14.5 11L14 16"
                          stroke="currentColor"
                          strokeWidth="1.5"
                          strokeLinecap="round"
                        />
                      </svg>
                    </button>
                  </Tippy>
                </div>
              ),
            },
          ]}
          totalRecords={recordsData.all_counts}
          recordsPerPage={pageSize}
          page={page}
          onPageChange={(p) => setPage(p)}
          recordsPerPageOptions={PAGE_SIZES}
          onRecordsPerPageChange={(newPageSize) => {
            setPageSize(newPageSize);
            setPage(1);
          }}
          sortStatus={sortStatus}
          onSortStatusChange={setSortStatus}
          minHeight={200}
          paginationText={({ from, to, totalRecords }) =>
            `Showing  ${from} to ${to} of ${totalRecords} entries`
          }
        />
      </div>
      <DeleteProjectModal
        title="Delete Project"
        message="Are you sure you want to delete this project?"
        isOpen={isdeleteProjectModal}
        onClose={() => setIsDeleteProjectModal(false)}
        onDelete={deleteProject}
      />
      <ManageProjectModal
        ManageProjectId={managedProjectId}
        isOpen={isManageProjectModal}
        onClose={onCloseManageProject}
        onSave={onSaveManageProject}
      />
    </div>
  );
};

export default Projects;

// src/UI/Angular/src/app/module/project/pages/list-projects/list-projects.component.ts
import { NgClass, NgStyle } from '@angular/common';
import { Component, ViewChild, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { DataTableModule, colDef } from '@bhplugin/ng-datatable';
import { PaginationFilter } from '../../../../core/models/pagination-filter.interface';
import { FilterService } from '../../../../core/services/filter.service';
import { AlertService } from '../../../../shared/services/alert.service';
import { ButtonComponent } from '../../../../shared/ui/button/button.component';
import { DeleteConfirmationModalComponent } from '../../../../shared/ui/delete-confirmation-modal/delete-confirmation-modal.component';
import { ManageProjectModalComponent } from '../../components/manage-project-modal/manage-project-modal.component';
import { ProjectService } from '../../services/project.service';

@Component({
  selector: 'app-list-projects',
  standalone: true,
  imports: [
    NgClass,
    NgStyle,
    DataTableModule,
    FormsModule,
    ButtonComponent,
    ManageProjectModalComponent,
    DeleteConfirmationModalComponent,
  ],
  templateUrl: './list-projects.component.html',
  styleUrl: './list-projects.component.css',
})
export class ListProjectsComponent {
  @ViewChild('manageProjectModalComponent')
  manageProjectModalComponent!: ManageProjectModalComponent;
  @ViewChild('deleteProjectModal')
  deleteProjectModal!: DeleteConfirmationModalComponent;

  projectService = inject(ProjectService);
  filterService = inject(FilterService);
  alertService = inject(AlertService);
  timer: any;
  deleteProjectId = '';
  editProjectId = '';

  params: PaginationFilter;

  loading: boolean = true;
  cols: Array<colDef> = [
    { field: 'projectName', title: 'Project Name' },
    { field: 'startDateDisplay', title: 'Start Date' },
    { field: 'endDateDisplay', title: 'End Date' },
    { field: 'estimatedHours', title: 'Estimated Hours' },
    {
      field: 'action',
      title: 'Action',
      sort: false,
      filter: false,
      headerClass: 'justify-center',
    },
  ];

  rows: Array<any> = [];
  total_rows: number = 0;

  constructor() {
    this.params = { ...this.filterService.defaultFilter };
    this.getProject();
  }

  async getProject() {
    this.loading = true;
    this.projectService.getProjects(this.params).subscribe((data) => {
      this.rows = data?.data;
      this.total_rows = data?.totalCount;
      this.loading = false;
    });
  }

  changeServer(data: any) {
    this.params.PageNumber = data.current_page;
    this.params.PageSize = data.pagesize;
    this.params.OrderBy = [
      this.getSortColumnName(data.sort_column) + ' ' + data.sort_direction,
    ];
    this.params = this.filterService.generateFilter(
      data.column_filters,
      this.params,
    );
    if (data.change_type === 'filter') {
      this.filterProjects();
    } else {
      this.getProject();
    }
  }

  filterProjects() {
    clearTimeout(this.timer);
    this.timer = setTimeout(() => {
      this.getProject();
    }, 300);
  }

  getBadgeColor(status: string): string {
    switch (status) {
      case 'Active':
        return 'badge-outline-success';
      case 'Inactive':
        return 'badge-outline-danger';
      default:
        return 'badge-outline-info';
    }
  }

  getSortColumnName(column: string): string {
    switch (column) {
      case 'startDateDisplay':
        return 'startDate';
      case 'endDateDisplay':
        return 'endDate';
      default:
        return column;
    }
  }

  openCreateProjectModal() {
    this.manageProjectModalComponent.open();
  }

  deleteProject(id: string) {
    this.deleteProjectModal.open();
    this.deleteProjectId = id;
  }

  editProject(id: string) {
    this.editProjectId = id;
    this.openCreateProjectModal();
  }

  onDelete() {
    this.projectService
      .deleteProject(this.deleteProjectId)
      .subscribe((data) => {
        this.alertService.showMessage(data.message);
        this.getProject();
        this.deleteProjectModal.close();
      });
  }

  onSave() {
    this.getProject();
    this.onCancel();
  }

  onCancel() {
    this.deleteProjectId = this.editProjectId = '';
  }
}

<div class="panel mt-6 pb-0">
  <div class="mb-5 flex flex-col gap-5 md:flex-row md:items-center">
    <h5 class="text-lg font-semibold dark:text-white-light">Projects</h5>
    <div class="ltr:ml-auto rtl:mr-auto">
      <app-button
        text="Create"
        type="button"
        classes="btn-outline-primary btn-sm w-full"
        class="d-block"
        (click)="openCreateProjectModal()"
      ></app-button>
    </div>
  </div>

  <div class="datatable">
    <ng-datatable
      [rows]="rows"
      [columns]="cols"
      [loading]="loading"
      [totalRows]="total_rows"
      [isServerMode]="true"
      [pageSize]="params.PageSize"
      [pageSizeOptions]="[10, 15, 30, 50]"
      [sortable]="true"
      paginationInfo="{0} to {1} of {2}"
      (changeServer)="changeServer($event)"
      skin="whitespace-nowrap table-hover"
    >
      <ng-template slot="status" let-value="data">
        <span class="badge" [ngClass]="getBadgeColor(value.status)">{{
          value.status
        }}</span>
      </ng-template>
      <ng-template slot="action" let-value="data">
        <ul class="flex items-center justify-center gap-2">
          <li>
            <a
              href="javascript:;"
              ngxTippy
              data-tippy-content="Edit"
              (click)="editProject(value.id)"
            >
              <svg
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
                class="h-4.5 w-4.5 text-success"
              >
                <path
                  d="M15.2869 3.15178L14.3601 4.07866L5.83882 12.5999L5.83881 12.5999C5.26166 13.1771 4.97308 13.4656 4.7249 13.7838C4.43213 14.1592 4.18114 14.5653 3.97634 14.995C3.80273 15.3593 3.67368 15.7465 3.41556 16.5208L2.32181 19.8021L2.05445 20.6042C1.92743 20.9852 2.0266 21.4053 2.31063 21.6894C2.59466 21.9734 3.01478 22.0726 3.39584 21.9456L4.19792 21.6782L7.47918 20.5844L7.47919 20.5844C8.25353 20.3263 8.6407 20.1973 9.00498 20.0237C9.43469 19.8189 9.84082 19.5679 10.2162 19.2751C10.5344 19.0269 10.8229 18.7383 11.4001 18.1612L11.4001 18.1612L19.9213 9.63993L20.8482 8.71306C22.3839 7.17735 22.3839 4.68748 20.8482 3.15178C19.3125 1.61607 16.8226 1.61607 15.2869 3.15178Z"
                  stroke="currentColor"
                  stroke-width="1.5"
                />
                <path
                  opacity="0.5"
                  d="M14.36 4.07812C14.36 4.07812 14.4759 6.04774 16.2138 7.78564C17.9517 9.52354 19.9213 9.6394 19.9213 9.6394M4.19789 21.6777L2.32178 19.8015"
                  stroke="currentColor"
                  stroke-width="1.5"
                />
              </svg>
            </a>
          </li>
          <li>
            <a
              href="javascript:;"
              ngxTippy
              data-tippy-content="Delete"
              (click)="deleteProject(value.id)"
            >
              <svg
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
                class="h-5 w-5 text-danger"
              >
                <path
                  d="M20.5001 6H3.5"
                  stroke="currentColor"
                  stroke-width="1.5"
                  stroke-linecap="round"
                />
                <path
                  d="M18.8334 8.5L18.3735 15.3991C18.1965 18.054 18.108 19.3815 17.243 20.1907C16.378 21 15.0476 21 12.3868 21H11.6134C8.9526 21 7.6222 21 6.75719 20.1907C5.89218 19.3815 5.80368 18.054 5.62669 15.3991L5.16675 8.5"
                  stroke="currentColor"
                  stroke-width="1.5"
                  stroke-linecap="round"
                />
                <path
                  opacity="0.5"
                  d="M9.5 11L10 16"
                  stroke="currentColor"
                  stroke-width="1.5"
                  stroke-linecap="round"
                />
                <path
                  opacity="0.5"
                  d="M14.5 11L14 16"
                  stroke="currentColor"
                  stroke-width="1.5"
                  stroke-linecap="round"
                />
                <path
                  opacity="0.5"
                  d="M6.5 6C6.55588 6 6.58382 6 6.60915 5.99936C7.43259 5.97849 8.15902 5.45491 8.43922 4.68032C8.44784 4.65649 8.45667 4.62999 8.47434 4.57697L8.57143 4.28571C8.65431 4.03708 8.69575 3.91276 8.75071 3.8072C8.97001 3.38607 9.37574 3.09364 9.84461 3.01877C9.96213 3 10.0932 3 10.3553 3H13.6447C13.9068 3 14.0379 3 14.1554 3.01877C14.6243 3.09364 15.03 3.38607 15.2493 3.8072C15.3043 3.91276 15.3457 4.03708 15.4286 4.28571L15.5257 4.57697C15.5433 4.62992 15.5522 4.65651 15.5608 4.68032C15.841 5.45491 16.5674 5.97849 17.3909 5.99936C17.4162 6 17.4441 6 17.5 6"
                  stroke="currentColor"
                  stroke-width="1.5"
                />
              </svg>
            </a>
          </li>
        </ul>
      </ng-template>
    </ng-datatable>
  </div>
</div>
<app-manage-project-modal
  [projectId]="editProjectId"
  #manageProjectModalComponent
  (saved)="onSave()"
  (discard)="onCancel()"
></app-manage-project-modal>
<app-delete-confirmation-modal
  #deleteProjectModal
  Title="Delete Project"
  Message="Are you sure you want to delete this project?"
  (onDelete)="onDelete()"
  (onCancel)="onCancel()"
></app-delete-confirmation-modal>
